default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: maradona_development

test:
  <<: *default
  database: maradona_test

production:
  <<: *default
  database: maradona_production
  username: maradona
  password: <%= ENV['MARADONA_DATABASE_PASSWORD'] %>
